o = vim.opt
c = vim.cmd

o.backup = false
o.clipboard = "unnamedplus"
o.cmdheight = 2
o.completeopt = { "menuone", "noselect" }
o.conceallevel = 0
o.fileencoding = "utf-8"
o.hlsearch = true
o.ignorecase = true
o.mouse = "a"
o.pumheight = 10
o.showtabline = 4
o.smartcase = true
o.smartindent = true
o.splitbelow = true
o.splitright = true
o.swapfile = false
o.termguicolors = true
o.timeoutlen = 1000
o.undofile = true
o.updatetime = 300
o.writebackup = false
o.expandtab = tab
o.shiftwidth = 4
o.tabstop = 3
o.number = true
o.relativenumber = false
o.signcolumn = "yes"
o.wrap = true
o.scrolloff = 8
o.sidescrolloff = 8
o.guifont = "Jetbrains Mono"
